# Black formatting
[tool.black]
line-length = 80
include = '\.pyi?$'
exclude = '''
/(
      .eggs         # exclude a few common directories in the
    | .git          # root of the project
    | .hg
    | .mypy_cache
    | .tox
    | venv
    | _build
    | buck-out
    | build
    | dist
    | code/ui/node_modules
  )/
'''
[tool.isort]
skip_glob = [ "data/cache/*" ]

[tool.pytest.ini_options]
pythonpath = [
  "code"
]
